import type { FormEvent, KeyboardEvent } from 'react';
import { useState } from 'react';
import { useLocale } from '../../i18n/LocaleContext';
import type { ApprovalReview, CoreStatus, DesktopCommandResponse, Mission, MissionEvent } from '../../types/desktop';

export type DesktopCommandResult = { state: string; text: string };
type ReviewState = 'idle'|'loading'|'ready'|'stale'|'truncated'|'unavailable'|'error';
type Props = { coreStatus: CoreStatus; submitting: boolean; commandResult: DesktopCommandResult | null; onSubmitCommand: (message: string) => Promise<DesktopCommandResponse>; mission: Mission | null; missionEvents: MissionEvent[]; decisionBusy: string | null; decisionMessage: string | null; onDecision: (taskId: string, approvalId: string, version: number, decision: 'approve' | 'reject') => Promise<void>; review: ApprovalReview | null; reviewState: ReviewState; reviewMessage: string | null; onRefreshReview: () => void };

function ReviewPanel({ review, state, message, onRefresh }: { review: ApprovalReview | null; state: ReviewState; message: string | null; onRefresh: () => void }) {
  const { t } = useLocale();
  return <>
    <div className="reviewToolbar"><button type="button" onClick={onRefresh}>{t.refreshReview}</button><span>{state === 'loading' ? t.reviewLoading : state === 'stale' ? t.reviewStale : state === 'truncated' ? t.reviewTruncated : state === 'unavailable' ? t.reviewUnavailable : ''}</span></div>
    {review && <div className="changeReview"><h3>{t.changeReview}</h3>{review.title && <p><b>{review.title}</b></p>}{review.reason && <p>{review.reason}</p>}{review.affected_files.length > 0 && <div><b>{t.affectedFiles}</b><ul>{review.affected_files.map(file => <li key={file}>{file}</li>)}</ul></div>}{review.operation_count !== null && <p><b>{t.operations}:</b> {review.operation_count} {review.operation_kinds.join(', ')}</p>}{review.preview && <div><b>{t.preview}</b><pre className="reviewCode">{JSON.stringify(review.preview, null, 2)}</pre></div>}{review.evidence.length > 0 && <div><b>{t.evidence}</b><pre className="reviewCode">{JSON.stringify(review.evidence, null, 2)}</pre></div>}{review.truncated && <p className="composerHint">{t.reviewTruncated}</p>}</div>}
    {message && <span className="composerHint">{message}</span>}
  </>;
}

export function HomeWorkbench({ coreStatus, submitting, commandResult, onSubmitCommand, mission, missionEvents, decisionBusy, decisionMessage, onDecision, review, reviewState, reviewMessage, onRefreshReview }: Props) {
  const { t } = useLocale(); const [draft, setDraft] = useState(''); const coreReady = coreStatus.state === 'ready'; const canSubmit = draft.trim().length > 0 && coreReady && !submitting;
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const message = draft.trim(); if (!message || !coreReady || submitting) return; void onSubmitCommand(message).then(() => setDraft('')).catch(() => undefined); };
  const onKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } };
  const coreLabel = coreReady ? t.coreReady : coreStatus.state === 'auth_required' ? t.coreAuthRequired : t.coreOffline; const readinessHint = coreStatus.state === 'auth_required' ? t.authHint : t.offlineHint; const pending = mission?.tasks.find(task => task.approval_state === 'pending' && task.approval_id);
  const taskRows = mission?.tasks.map(task => <div className="missionTask" key={task.id}><span>{task.title}</span><span>{task.status}</span>{task.assigned_agent && <small>{task.assigned_agent}</small>}</div>);
  const eventRows = missionEvents.map(event => <div key={`${event.sequence}-${event.event_type}`}><span>{event.event_type}</span><small>{event.message} · {event.occurred_at}</small></div>);
  return <section className="home"><div className="eyebrow">{t.eyebrow}</div><h1>{t.heading}</h1><p>{t.support}</p>
    <form className="commandSurface" onSubmit={handleSubmit}><label htmlFor="desktop-command">{t.composerLabel}</label><span className="composerHint">{t.composerHint}</span><textarea id="desktop-command" value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={onKeyDown} placeholder={t.composerPlaceholder} maxLength={20000} rows={4} /><div className="composerMeta"><span className={coreReady ? 'coreReady' : 'coreOffline'}>{coreLabel}</span><button type="submit" disabled={!canSubmit}>{submitting ? t.sending : t.send}</button></div><span className="composerHint">{t.keyboardHint}</span></form>
    {!coreReady && <div className="composerOffline">{readinessHint}</div>}{commandResult && <div className="commandResult" role="status"><b>{t.latestResult}</b><span>{commandResult.text}</span></div>}
    {mission && <section className="missionControl" aria-live="polite"><div className="missionHeader"><div><div className="eyebrow">{t.missionControl}</div><h2>{mission.goal}</h2><span>{mission.id} · {mission.status}</span></div></div><div className="missionTasks"><b>{t.taskProgress}</b>{taskRows}</div>
      {pending && <div className="approvalCard"><b>{t.pendingApproval}</b><p>{pending.approval_description || pending.last_approval_message || t.approvalNeedsReview}</p><small>{pending.id} · {pending.approval_id} · v{pending.approval_version}</small><ReviewPanel review={review} state={reviewState} message={reviewMessage} onRefresh={onRefreshReview} /><div><button type="button" disabled={decisionBusy !== null || reviewState === 'loading' || reviewState === 'stale' || reviewState === 'error'} onClick={() => void onDecision(pending.id, pending.approval_id || '', pending.approval_version, 'approve')}>{decisionBusy === pending.id ? t.decisionSending : t.approve}</button><button type="button" disabled={decisionBusy !== null || reviewState === 'stale'} onClick={() => void onDecision(pending.id, pending.approval_id || '', pending.approval_version, 'reject')}>{t.reject}</button></div>{decisionMessage && <span className="composerHint">{decisionMessage}</span>}</div>}
      <div className="missionEvents"><b>{t.nav.activity}</b>{eventRows}</div></section>}
    <div className="quick"><button>{t.start}</button><button>{t.open}</button><button>{t.review}</button></div><div className="system"><div><b>{t.core.toUpperCase()}</b><span>{coreStatus.state === 'ready' ? t.ready : coreStatus.state === 'auth_required' ? t.authRequired : coreStatus.state === 'protocol_error' ? t.protocolError : coreStatus.state === 'preview' ? t.preview : t.offline}</span></div><div className="authority"><span>{t.filesystem} <b>{t.denied}</b></span><span>{t.shell} <b>{t.denied}</b></span><span>{t.process} <b>{t.denied}</b></span><span>{t.remote} <b>{t.denied}</b></span><span>{t.authority} <b>Prometheus Core</b></span></div></div></section>;
}
