import { useEffect, useState } from 'react';
import { useLocale } from '../../i18n/LocaleContext';
import { getNativeCapabilities, getNativeEnvironment, openExternalUrl, readClipboardText, revealNativePath, selectNativeFile, selectNativeFolder, showNativeNotification, writeClipboardText } from '../../lib/desktopBridge';
import type { NativeCapability, NativeEnvironmentInfo } from '../../types/desktop';

export function NativeIntegrationWorkbench() {
  const { t } = useLocale();
  const [capabilities, setCapabilities] = useState<NativeCapability[]>([]); const [environment, setEnvironment] = useState<NativeEnvironmentInfo | null>(null); const [selectedPath, setSelectedPath] = useState<string | null>(null); const [clipboard, setClipboard] = useState(''); const [busy, setBusy] = useState<string | null>(null); const [result, setResult] = useState<string | null>(null);
  useEffect(() => { let disposed = false; void Promise.all([getNativeCapabilities(), getNativeEnvironment()]).then(([caps, env]) => { if (!disposed) { setCapabilities(caps); setEnvironment(env); } }).catch(() => { if (!disposed) setResult(t.nativeUnavailable); }); return () => { disposed = true; }; }, [t.nativeUnavailable]);
  const perform = async (name: string, operation: () => Promise<void>) => { if (busy) return; setBusy(name); setResult(null); try { await operation(); setResult(t.operationSucceeded); } catch { setResult(t.operationFailed); } finally { setBusy(null); } };
  const choose = async (kind: 'file' | 'folder') => perform(kind, async () => { const path = kind === 'file' ? await selectNativeFile() : await selectNativeFolder(); if (path) setSelectedPath(path); });
  return <div className="missionEvents nativeIntegration"><b>{t.nativeIntegration}</b>{environment && <><small>Prometheus {environment.application_version} · {environment.runtime_platform} · {environment.architecture}</small><div className="releaseDiagnostics"><b>{t.releaseDiagnostics}</b><small>{t.coreRuntimeRequirement}: {t.developmentWorkspacePython}</small><small>{t.updaterNotConfigured}</small><small>{t.signingNotConfigured}</small></div></>}<div className="nativeCapabilities">{capabilities.map(capability => <span key={capability.capability_id}>{capability.capability_id}: {capability.available ? t.available : t.unavailable}</span>)}</div><div className="language"><button disabled={busy !== null} onClick={() => void choose('file')}>{t.chooseFile}</button><button disabled={busy !== null} onClick={() => void choose('folder')}>{t.chooseFolder}</button><button disabled={!selectedPath || busy !== null} onClick={() => selectedPath && void perform('reveal', () => revealNativePath(selectedPath))}>{t.revealExplorer}</button></div>{selectedPath && <small className="pathValue">{t.selectedPath}: {selectedPath}</small>}<textarea aria-label={t.clipboardText} value={clipboard} maxLength={65536} onChange={event => setClipboard(event.target.value)} placeholder={t.clipboardText} /><div className="language"><button disabled={busy !== null} onClick={() => void perform('read', async () => setClipboard(await readClipboardText()))}>{t.pasteClipboard}</button><button disabled={busy !== null} onClick={() => void perform('write', () => writeClipboardText(clipboard))}>{t.copyClipboard}</button><button disabled={busy !== null} onClick={() => void perform('notify', () => showNativeNotification('Prometheus', t.notificationBody))}>{t.testNotification}</button><button disabled={busy !== null} onClick={() => void perform('link', () => openExternalUrl('https://github.com/resatkahraman/Prometheus'))}>{t.openProjectPage}</button></div>{result && <small role="status">{result}</small>}</div>;
}
