import { useEffect, useRef, useState } from 'react';
import { ActivityRail } from './components/navigation/ActivityRail';
import { ContextSidebar } from './components/navigation/ContextSidebar';
import { TitleBar } from './components/window/TitleBar';
import { StatusBar } from './components/status/StatusBar';
import { HomeWorkbench, type DesktopCommandResult } from './components/workbench/HomeWorkbench';
import { InspectorPanel } from './components/workbench/InspectorPanel';
import { CommandCenter } from './components/command/CommandCenter';
import { approveDesktopTask, getDesktopApprovalReview, getDesktopBootstrap, getDesktopCoreStatus, getDesktopMission, getDesktopMissionEvents, rejectDesktopTask, submitDesktopCommand } from './lib/desktopBridge';
import type { ApprovalReview, CoreStatus, DesktopCommandResponse, Mission, MissionEvent, NavigationView } from './types/desktop';
import { useLocale } from './i18n/LocaleContext';

export default function App() {
  const [view, setView] = useState<NavigationView>('home'); const [open, setOpen] = useState(false);
  const [coreStatus, setCoreStatus] = useState<CoreStatus>({ state: 'connecting', code: 'connecting', message: 'Connecting...' }); const [submitting, setSubmitting] = useState(false); const [commandResult, setCommandResult] = useState<DesktopCommandResult | null>(null);
  const [missionId, setMissionId] = useState<string | null>(null); const [mission, setMission] = useState<Mission | null>(null); const [missionEvents, setMissionEvents] = useState<MissionEvent[]>([]); const [decisionBusy, setDecisionBusy] = useState<string | null>(null); const [decisionMessage, setDecisionMessage] = useState<string | null>(null);
  const [review, setReview] = useState<ApprovalReview | null>(null); const [reviewState, setReviewState] = useState<'idle'|'loading'|'ready'|'stale'|'truncated'|'unavailable'|'error'>('idle'); const [reviewMessage, setReviewMessage] = useState<string | null>(null); const [reviewNonce, setReviewNonce] = useState(0); const reviewGeneration = useRef(0); const missionGeneration = useRef(0); const { t, locale, setLocale } = useLocale();
  useEffect(() => { let disposed = false; let inFlight = false; const refresh = async () => { if (inFlight) return; inFlight = true; try { const status = await getDesktopCoreStatus(); if (!disposed) setCoreStatus(status); } finally { inFlight = false; } }; void getDesktopBootstrap().then(refresh).catch(() => { if (!disposed) setCoreStatus({ state: 'core_error', code: 'core_error', message: 'Core bootstrap failed.' }); }); const timer = window.setInterval(() => void refresh(), 5000); return () => { disposed = true; window.clearInterval(timer); }; }, []);
  useEffect(() => { if (!missionId) { setMission(null); setMissionEvents([]); setReview(null); setReviewState('idle'); return; } const generation = ++missionGeneration.current; let disposed = false; let inFlight = false; const refresh = async () => { if (inFlight) return; inFlight = true; try { const [nextMission, nextEvents] = await Promise.all([getDesktopMission(missionId), getDesktopMissionEvents(missionId)]); if (!disposed && missionGeneration.current === generation) { setMission(nextMission); setMissionEvents(nextEvents.events); } } catch (error) { if (!disposed && missionGeneration.current === generation) setDecisionMessage(typeof error === 'object' && error && 'code' in error ? String(error.code) : t.missionLoadFailed); } finally { inFlight = false; } }; void refresh(); const timer = window.setInterval(() => { if (!mission?.status || !['completed', 'failed', 'cancelled'].includes(mission.status)) void refresh(); }, 2000); const focus = () => void refresh(); window.addEventListener('focus', focus); return () => { disposed = true; window.clearInterval(timer); window.removeEventListener('focus', focus); }; }, [missionId, mission?.status, t.missionLoadFailed]);
  const pending = mission?.tasks.find(task => task.approval_state === 'pending' && task.approval_id) ?? null;
  useEffect(() => { if (!missionId || !pending?.approval_id) { setReview(null); setReviewState('idle'); return; } const generation = ++reviewGeneration.current; let disposed = false; setReviewState('loading'); setReviewMessage(null); void getDesktopApprovalReview(missionId, pending.approval_id).then(value => { if (!disposed && reviewGeneration.current === generation) { setReview(value); setReviewState(value.truncated ? 'truncated' : value.preview ? 'ready' : 'unavailable'); } }).catch(error => { if (!disposed && reviewGeneration.current === generation) { setReview(null); setReviewState('error'); setReviewMessage(typeof error === 'object' && error && 'code' in error ? String(error.code) : t.reviewUnavailable); } }); return () => { disposed = true; }; }, [missionId, pending?.approval_id, pending?.approval_version, reviewNonce, t.reviewUnavailable]);
  const refreshReview = () => { if (missionId && pending?.approval_id) { setReviewNonce(value => value + 1); } };
  const handleSubmitCommand = async (message: string): Promise<DesktopCommandResponse> => { setSubmitting(true); setCommandResult({ state: 'submitting', text: t.sending }); try { const response = await submitDesktopCommand(message); setMissionId(response.mission_id || null); setCommandResult({ state: response.requires_approval ? 'requires_approval' : response.status, text: response.summary || t.commandAccepted }); return response; } catch (error) { const code = typeof error === 'object' && error && 'code' in error ? String(error.code) : 'core_error'; setCommandResult({ state: code === 'timeout' || code === 'core_offline' ? 'uncertain' : 'error', text: code === 'timeout' || code === 'core_offline' ? t.commandUncertain : t.commandFailed }); throw error; } finally { setSubmitting(false); } };
  const handleDecision = async (taskId: string, approvalId: string, version: number, decision: 'approve' | 'reject') => { if (!missionId || decisionBusy || reviewState === 'loading' || reviewState === 'stale' || reviewState === 'error') return; setDecisionBusy(taskId); setDecisionMessage(null); try { const result = decision === 'approve' ? await approveDesktopTask(missionId, taskId, approvalId, version) : await rejectDesktopTask(missionId, taskId, approvalId, version); setMission(result); setReviewState('stale'); setDecisionMessage(t.decisionAccepted); } catch (error) { const code = typeof error === 'object' && error && 'code' in error ? String(error.code) : 'core_error'; setDecisionMessage(code === 'uncertain' ? t.decisionUncertain : t.missionLoadFailed); } finally { setDecisionBusy(null); } };
  return <div className="app"><TitleBar onSearch={() => setOpen(true)} /><div className="body"><ActivityRail active={view} onSelect={setView} /><ContextSidebar active={view} onSelect={setView} /><main>{view === 'home' ? <HomeWorkbench coreStatus={coreStatus} submitting={submitting} commandResult={commandResult} onSubmitCommand={handleSubmitCommand} mission={mission} missionEvents={missionEvents} decisionBusy={decisionBusy} decisionMessage={decisionMessage} onDecision={handleDecision} review={review} reviewState={reviewState} reviewMessage={reviewMessage} onRefreshReview={refreshReview} /> : view === 'settings' ? <section className="empty"><div className="eyebrow">{t.nav.settings.toUpperCase()}</div><h1>{t.nav.settings}</h1><p>{t.core} · {t.notConfigured}</p><div className="language"><div className="eyebrow">{t.settingsTitle}</div><button className={locale === 'tr' ? 'selected' : ''} onClick={() => setLocale('tr')}>{t.switchTr}</button><button className={locale === 'en' ? 'selected' : ''} onClick={() => setLocale('en')}>{t.switchEn}</button></div></section> : <section className="empty"><div className="eyebrow">{t.nav[view].toUpperCase()}</div><h1>{t.nav[view]}</h1><p>{t.empty}</p></section>}</main><InspectorPanel coreStatus={coreStatus} /></div><StatusBar state={coreStatus.state} />{open && <CommandCenter onClose={() => setOpen(false)} onSelect={setView} />}</div>;
}
