ARENA_UI = r"""<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Prometheus Arena</title>
  <style>
    :root{color-scheme:dark;--bg:#0b1020;--panel:#121a2f;--line:#263453;--text:#e8edf8;--muted:#95a4bf;--ok:#52d68a;--bad:#ff6b7a;--accent:#7aa2ff;--warn:#ffca68}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 system-ui,sans-serif}
    main{max-width:1360px;margin:auto;padding:28px}.top,.toolbar{display:flex;gap:16px;align-items:end;justify-content:space-between;flex-wrap:wrap}
    h1{margin:0;font-size:30px}h2{margin-top:0}p{color:var(--muted)}select,button,input{background:var(--panel);border:1px solid var(--line);color:var(--text);padding:10px 12px;border-radius:9px}
    button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.45}.stats{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:12px;margin:22px 0}.card,.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px}.stat{font-size:24px;font-weight:700}.label{color:var(--muted);font-size:12px}
    table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid var(--line);text-align:left}tbody tr{cursor:pointer}tbody tr:hover{background:#18223c}.ok{color:var(--ok)}.bad{color:var(--bad)}.warn{color:var(--warn)}
    .grid{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.details{white-space:pre-wrap;overflow:auto;max-height:650px}.empty{color:var(--muted);padding:24px;text-align:center}.compare{margin-top:16px}.compare-head{display:flex;gap:12px;justify-content:space-between;align-items:center;flex-wrap:wrap}.selected{color:var(--muted)}
    .compare-grid{display:grid;grid-template-columns:.7fr 1.3fr;gap:16px;margin-top:14px}.highlights{margin:0;padding-left:20px}.metric-delta{font-variant-numeric:tabular-nums}.verdict{font-size:20px;font-weight:750}.checkbox{width:18px;height:18px;accent-color:var(--accent)}
    .diagnosis{white-space:normal;margin-bottom:18px}.diagnosis h3{margin:0 0 8px}.finding{border-left:3px solid var(--line);padding:10px 12px;margin:10px 0;background:#0e1629;border-radius:6px}.finding.critical,.finding.high{border-left-color:var(--bad)}.finding.medium{border-left-color:var(--warn)}.finding.low,.finding.info{border-left-color:var(--ok)}.finding ul{margin:7px 0;padding-left:19px}.next-action{color:var(--text)}.recovery{white-space:normal;margin-bottom:18px;padding:12px;border:1px solid var(--line);border-radius:9px;background:#0e1629}.recovery h3{margin:0 0 8px}.recovery ol{padding-left:22px}.recovery code{display:block;overflow:auto;padding:10px;background:#080d19;border-radius:7px;color:var(--ok)}.safeguards{color:var(--muted);font-size:12px}.execution{margin-top:12px;padding-top:12px;border-top:1px solid var(--line)}.execution input{width:100%;margin:8px 0}.execution-status{margin-top:8px;white-space:pre-wrap}.raw-title{border-top:1px solid var(--line);padding-top:14px}
    @media(max-width:900px){.grid,.compare-grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}table{font-size:12px}main{padding:16px}}
  </style>
</head>
<body><main>
  <div class="top"><div><h1>Prometheus Arena</h1><p>Koşu geçmişi, teşhis, A/B karşılaştırması ve açık onaylı tek seferlik recovery yürütmesi.</p></div>
  <div><select id="scenario"><option value="">Tüm senaryolar</option></select> <button id="refresh">Yenile</button></div></div>
  <section class="stats"><div class="card"><div id="runs" class="stat">0</div><div class="label">Koşu</div></div><div class="card"><div id="passes" class="stat">0</div><div class="label">Tamamlanan</div></div><div class="card"><div id="avg" class="stat">0</div><div class="label">Ortalama skor</div></div><div class="card"><div id="tokens" class="stat">0</div><div class="label">Toplam token</div></div></section>
  <section class="grid"><div class="panel"><div class="toolbar"><div><strong>Koşular</strong><div id="selection" class="selected">Karşılaştırmak için iki koşu seç.</div></div><div><button id="compare" disabled>Koşuları karşılaştır</button> <button id="clear" disabled>Seçimi temizle</button></div></div><table><thead><tr><th></th><th>Senaryo</th><th>Durum</th><th>Skor</th><th>Çağrı</th><th>Süre</th></tr></thead><tbody id="history"></tbody></table><div id="empty" class="empty" hidden>Kayıt bulunamadı.</div></div><div class="panel"><h2>Koşu detayı</h2><div id="diagnosis" class="diagnosis empty">Bir koşu seçildiğinde otomatik teşhis burada görünür.</div><div id="recovery" class="recovery empty">Güvenli kurtarma planı burada görünür.</div><h3 class="raw-title">Ham koşu kanıtı</h3><div id="detail" class="details empty">Bir koşu seç.</div></div></section>
  <section class="panel compare"><div class="compare-head"><div><h2>Koşu karşılaştırması</h2><div id="verdict" class="verdict">İki koşu seçilmedi.</div></div><div id="scenario-note" class="selected"></div></div><div id="comparison" class="empty">Aynı senaryonun önceki ve sonraki koşularını seçerek kalite, doğrulama ve maliyet farklarını incele.</div></section>
</main><script>
const q=s=>document.querySelector(s);let rows=[];let selected=[];let activeRunId=null;let recoveryPoll=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function format(v){if(typeof v!=='number')return esc(v);return Number.isInteger(v)?v.toLocaleString('tr-TR'):v.toLocaleString('tr-TR',{maximumFractionDigits:1});}
function outcomeClass(v){return v==='improved'?'ok':v==='regressed'?'bad':v==='mixed'?'warn':'';}
function updateSelection(){selected=selected.filter(id=>rows.some(row=>row.run_id===id));q('#selection').textContent=selected.length?selected.map((id,index)=>`${index===0?'A':'B'}: ${id}`).join(' · '):'Karşılaştırmak için iki koşu seç.';q('#compare').disabled=selected.length!==2;q('#clear').disabled=selected.length===0;for(const box of q('#history').querySelectorAll('.checkbox'))box.checked=selected.includes(box.dataset.id);}
function toggle(id,checked){if(checked){if(selected.length>=2){alert('En fazla iki koşu seçilebilir.');updateSelection();return;}selected.push(id);}else selected=selected.filter(item=>item!==id);updateSelection();}
async function loadScenarios(){const r=await fetch('/v1/arena/scenarios');const data=await r.json();for(const s of data){q('#scenario').insertAdjacentHTML('beforeend',`<option value="${esc(s.id)}">${esc(s.title)}</option>`);}}
function render(){q('#runs').textContent=rows.length;q('#passes').textContent=rows.filter(r=>r.status==='completed').length;q('#avg').textContent=rows.length?(rows.reduce((a,r)=>a+r.score,0)/rows.length).toFixed(1):'0';q('#tokens').textContent=rows.reduce((a,r)=>a+r.total_tokens,0).toLocaleString('tr-TR');q('#empty').hidden=rows.length>0;q('#history').innerHTML=rows.map(r=>`<tr data-id="${esc(r.run_id)}"><td><input class="checkbox" type="checkbox" data-id="${esc(r.run_id)}" aria-label="Karşılaştırma için seç"></td><td>${esc(r.scenario_title)}</td><td class="${r.status==='completed'?'ok':'bad'}">${esc(r.status)}</td><td>${r.score.toFixed(1)}</td><td>${r.model_calls}</td><td>${r.elapsed_seconds.toFixed(1)} sn</td></tr>`).join('');for(const tr of q('#history').children)tr.onclick=e=>{if(e.target.classList.contains('checkbox'))return;detail(tr.dataset.id);};for(const box of q('#history').querySelectorAll('.checkbox'))box.onchange=()=>toggle(box.dataset.id,box.checked);updateSelection();}
async function load(){const scenario=q('#scenario').value;const url='/v1/arena/history?limit=100'+(scenario?'&scenario_id='+encodeURIComponent(scenario):'');const r=await fetch(url);rows=await r.json();render();}
function renderDiagnosis(d){const primary=d.primary_issue||{};const findings=(d.findings||[]).map(item=>`<div class="finding ${esc(item.severity)}"><strong>${esc(item.title)}</strong><p>${esc(item.summary)}</p><ul>${(item.evidence||[]).map(value=>`<li>${esc(value)}</li>`).join('')}</ul><div class="next-action"><strong>Sonraki adım:</strong> ${esc(item.next_action)}</div></div>`).join('');q('#diagnosis').className='diagnosis';q('#diagnosis').innerHTML=`<h3>Otomatik teşhis · <span class="${d.health==='failed'?'bad':d.health==='warning'?'warn':'ok'}">${esc(d.health)}</span></h3><p><strong>Birincil konu:</strong> ${esc(primary.title||'Belirgin sorun yok')}</p>${findings}`;}
function renderRecovery(p){const steps=(p.steps||[]).map(item=>`<li><strong>${esc(item.title)}</strong><br>${esc(item.detail)}</li>`).join('');const command=p.command_preview?`<p><strong>Komut önizlemesi:</strong><code>${esc(p.command_preview)}</code></p>`:'';const approval=p.approval_phrase?`<p><strong>Gerekli onay cümlesi:</strong><code>${esc(p.approval_phrase)}</code></p>`:'';const execution=p.execution_available?`<div class="execution"><strong>Onaylı recovery yürütmesi</strong><p>Yukarıdaki onay cümlesini aynen yazarak yeni ve izole bir Arena koşusunu yalnızca bir kez başlat.</p><input id="recovery-approval" autocomplete="off" placeholder="Onay cümlesini aynen yaz"><button id="start-recovery">Recovery koşusunu başlat</button><div id="execution-status" class="execution-status"></div></div>`:'';const safe=p.safeguards||{};q('#recovery').className='recovery';q('#recovery').innerHTML=`<h3>Kurtarma manifesti · <span class="${p.decision==='ready_for_approval'?'warn':p.decision==='blocked'?'bad':'ok'}">${esc(p.decision)}</span></h3><p><strong>${esc(p.title)}</strong></p><p>${esc(p.summary)}</p><ol>${steps}</ol>${approval}${command}<div class="safeguards">Otomatik çalıştırma: ${safe.automatic_execution?'açık':'kapalı'} · Kaynak kanıt korunur: ${safe.preserve_source_run?'evet':'hayır'} · Tek canlı koşu sınırı: ${safe.one_live_invocation_only?'evet':'hayır'}</div>${execution}`;const button=q('#start-recovery');if(button)button.onclick=()=>startRecovery(p);}
async function detail(id){activeRunId=id;if(recoveryPoll){clearInterval(recoveryPoll);recoveryPoll=null;}q('#detail').textContent='Yükleniyor…';q('#diagnosis').className='diagnosis empty';q('#diagnosis').textContent='Teşhis hazırlanıyor…';q('#recovery').className='recovery empty';q('#recovery').textContent='Kurtarma planı hazırlanıyor…';const [runResponse,diagnosisResponse,recoveryResponse]=await Promise.all([fetch('/v1/arena/runs/'+encodeURIComponent(id)),fetch('/v1/arena/runs/'+encodeURIComponent(id)+'/diagnosis'),fetch('/v1/arena/runs/'+encodeURIComponent(id)+'/recovery-plan')]);const d=await runResponse.json();const diagnosis=await diagnosisResponse.json();const recovery=await recoveryResponse.json();if(!runResponse.ok||!diagnosisResponse.ok||!recoveryResponse.ok){q('#diagnosis').className='diagnosis bad';q('#diagnosis').textContent=diagnosis.detail||d.detail||recovery.detail||'Koşu detayı yüklenemedi.';q('#recovery').className='recovery bad';q('#recovery').textContent=recovery.detail||'Kurtarma planı yüklenemedi.';return;}renderDiagnosis(diagnosis);renderRecovery(recovery);q('#detail').classList.remove('empty');q('#detail').textContent=JSON.stringify({run_id:d.run_id,scenario:d.scenario_title,status:d.status,score:d.score,elapsed_seconds:d.elapsed_seconds,usage:d.usage,coordination:d.coordination,tasks:d.tasks,handoffs:d.handoffs,event_counts:d.event_counts,notable_events:d.notable_events,verifications:d.verifications,failure_reason:d.failure_reason,database:d.database},null,2);}

async function startRecovery(plan){const input=q('#recovery-approval');const button=q('#start-recovery');const status=q('#execution-status');if(!input||!button||!status||!activeRunId)return;const phrase=input.value.trim();if(phrase!==plan.approval_phrase){status.className='execution-status bad';status.textContent='Onay cümlesi tam olarak eşleşmiyor.';return;}button.disabled=true;status.className='execution-status warn';status.textContent='Kota preflight çalıştırılıyor ve recovery hazırlanıyor…';const response=await fetch('/v1/arena/runs/'+encodeURIComponent(activeRunId)+'/recovery-executions',{method:'POST',headers:{'Content-Type':'application/json','X-Prometheus-CSRF':'1'},body:JSON.stringify({approval_phrase:phrase})});const body=await response.json();if(!response.ok){button.disabled=false;status.className='execution-status bad';status.textContent=body.detail||'Recovery başlatılamadı.';return;}status.className='execution-status warn';status.textContent='Recovery yürütmesi başlatıldı: '+body.execution_id;pollRecovery(body.execution_id);}
function pollRecovery(executionId){if(recoveryPoll)clearInterval(recoveryPoll);const refresh=async()=>{const response=await fetch('/v1/arena/recovery-executions/'+encodeURIComponent(executionId));const body=await response.json();const status=q('#execution-status');if(!status)return;if(!response.ok){status.className='execution-status bad';status.textContent=body.detail||'Recovery durumu okunamadı.';clearInterval(recoveryPoll);recoveryPoll=null;return;}const lines=['Durum: '+body.status,'Senaryo: '+body.scenario_id,'Yeni history: '+body.history_path];if(body.product_status)lines.push('Ürün durumu: '+body.product_status);if(body.result_run_id)lines.push('Yeni run: '+body.result_run_id);if(body.result_workspace)lines.push('Yeni workspace: '+body.result_workspace);if(body.failure_reason)lines.push('Neden: '+body.failure_reason);status.className='execution-status '+(body.status==='failed'?'bad':body.status==='completed'?'ok':'warn');status.textContent=lines.join('\\n');if(body.status==='completed'||body.status==='failed'){clearInterval(recoveryPoll);recoveryPoll=null;await load();}};refresh();recoveryPoll=setInterval(refresh,2000);}
async function compare(){if(selected.length!==2)return;q('#comparison').className='empty';q('#comparison').textContent='Karşılaştırılıyor…';const url='/v1/arena/compare?base_run_id='+encodeURIComponent(selected[0])+'&candidate_run_id='+encodeURIComponent(selected[1]);const r=await fetch(url);const d=await r.json();if(!r.ok){q('#verdict').textContent='Karşılaştırma başarısız';q('#verdict').className='verdict bad';q('#comparison').textContent=d.detail||'Bilinmeyen hata';return;}q('#verdict').textContent=d.verdict;q('#verdict').className='verdict '+outcomeClass(d.verdict);q('#scenario-note').textContent=d.same_scenario?d.base.scenario_title:'Farklı senaryolar: kalite kararı verilmez';const metrics=d.metrics.map(m=>`<tr><td>${esc(m.label)}</td><td>${format(m.base)}</td><td>${format(m.candidate)}</td><td class="metric-delta ${outcomeClass(m.outcome)}">${m.delta>0?'+':''}${format(m.delta)}</td><td class="${outcomeClass(m.outcome)}">${esc(m.outcome)}</td></tr>`).join('');const highlights=d.highlights.length?`<ul class="highlights">${d.highlights.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`:'<p>Belirgin fark yok.</p>';q('#comparison').className='compare-grid';q('#comparison').innerHTML=`<div><h3>Öne çıkanlar</h3>${highlights}<p><strong>Kalite:</strong> <span class="${outcomeClass(d.quality_outcome)}">${esc(d.quality_outcome)}</span><br><strong>Verimlilik:</strong> <span class="${outcomeClass(d.efficiency_outcome)}">${esc(d.efficiency_outcome)}</span></p><p><strong>Yeni geçen doğrulamalar:</strong> ${esc(d.verifications.newly_passing.join(', ')||'Yok')}<br><strong>Yeni bozulan doğrulamalar:</strong> ${esc(d.verifications.newly_failing.join(', ')||'Yok')}</p></div><div><table><thead><tr><th>Metrik</th><th>A</th><th>B</th><th>Fark</th><th>Sonuç</th></tr></thead><tbody>${metrics}</tbody></table></div>`;}
q('#refresh').onclick=load;q('#scenario').onchange=load;q('#compare').onclick=compare;q('#clear').onclick=()=>{selected=[];updateSelection();q('#verdict').textContent='İki koşu seçilmedi.';q('#verdict').className='verdict';q('#scenario-note').textContent='';q('#comparison').className='empty';q('#comparison').textContent='Aynı senaryonun önceki ve sonraki koşularını seçerek kalite, doğrulama ve maliyet farklarını incele.';};Promise.all([loadScenarios(),load()]).catch(e=>q('#detail').textContent='Yükleme hatası: '+e);
</script></body></html>"""
