import type { Locale } from './locale';

const englishTranslations = {
  nav: { home: 'Home', command: 'Command', projects: 'Projects', missions: 'Missions', approvals: 'Approvals', changes: 'Changes', agents: 'Agents', activity: 'Activity', memory: 'Memory', settings: 'Settings' },
  brand: 'PROMETHEUS', center: 'Command Center', eyebrow: 'COMMAND CENTER', heading: 'Direct Prometheus with precision.', support: 'Direct Prometheus, inspect work, and review authority before execution.', quick: 'Quick Access', recent: 'Recent', start: 'Start Mission', open: 'Open Project', review: 'Review Approvals', ask: 'Ask Prometheus or start a command...', search: 'Search or command...', core: 'Prometheus Core', notConfigured: 'Not configured', preview: 'Preview mode', bridgeError: 'Native bridge error', filesystem: 'Filesystem', shell: 'Shell', process: 'Process', remote: 'Remote network', denied: 'Denied', authority: 'Canonical authority', safety: 'Safety', enforced: 'Enforced', surface: 'Surface', mode: 'Mode', desktop: 'Desktop', webview: 'Webview', restricted: 'Restricted', context: 'CONTEXT', security: 'SECURITY', navigate: 'NAVIGATE', actions: 'ACTIONS', settingsTitle: 'Language / Dil', switchTr: 'Switch to Turkish', switchEn: 'Switch to English', empty: 'Prometheus Core transport is not configured in DESKTOP-001.', projectsEmpty: 'Projects will appear here after the secure core bridge is connected.', desktopLabel: 'Prometheus Desktop', ready: 'Ready', offline: 'Offline', authRequired: 'Authentication required', protocolError: 'Protocol error', coreError: 'Core error', commandAccepted: 'Command accepted.', commandSubmitting: 'Submitting...', commandUnavailable: 'Core is not ready.', commandUncertain: 'The Core connection was interrupted. The command was not retried automatically. Check mission activity before submitting it again.', commandFailed: 'The Core could not accept the command.', requiresApproval: 'Requires approval', status: 'Status', transport: 'Transport', loopbackOnly: 'Loopback only', localNativeBridge: 'Local native bridge', latestResult: 'Latest command', composerLabel: 'Give Prometheus a command', composerHint: 'Describe what you want Prometheus to do.', composerPlaceholder: 'e.g. Check the latest task status in this project and summarize it...', send: 'Send', sending: 'Sending…', offlineHint: 'Prometheus Core must be connected before you can send a command.', authHint: 'You can type your command now. Core authentication is required before sending.', keyboardHint: 'Enter to send · Shift+Enter for a new line', coreReady: 'Core ready — you can send a command.', coreOffline: 'You can type your command now. Prometheus Core must be connected before sending.', coreAuthRequired: 'You can type your command now. Core authentication is required before sending.',
} as const;

const turkishTranslations = {
  nav: { home: 'Ana Sayfa', command: 'Komut', projects: 'Projeler', missions: 'Görevler', approvals: 'Onaylar', changes: 'Değişiklikler', agents: 'Ajanlar', activity: 'Etkinlik', memory: 'Hafıza', settings: 'Ayarlar' },
  brand: 'PROMETHEUS', center: 'Komuta Merkezi', eyebrow: 'KOMUTA MERKEZİ', heading: "Prometheus'u hassasiyetle yönetin.", support: "Prometheus'u yönlendirin, çalışmaları inceleyin ve yürütmeden önce yetkiyi gözden geçirin.", quick: 'Hızlı Erişim', recent: 'Son Kullanılanlar', start: 'Görev Başlat', open: 'Proje Aç', review: 'Onayları İncele', ask: "Prometheus'a sorun veya bir komut başlatın...", search: 'Ara veya komut gir...', core: 'Prometheus Core', notConfigured: 'Yapılandırılmadı', preview: 'Önizleme modu', bridgeError: 'Yerel köprü hatası', filesystem: 'Dosya sistemi', shell: 'Kabuk', process: 'İşlem', remote: 'Uzak ağ', denied: 'İzin yok', authority: 'Kanonik yetki', safety: 'Güvenlik', enforced: 'Etkin', surface: 'Yüzey', mode: 'Mod', desktop: 'Masaüstü', webview: 'Web görünümü', restricted: 'Kısıtlı', context: 'BAĞLAM', security: 'GÜVENLİK', navigate: 'GEZİN', actions: 'EYLEMLER', settingsTitle: 'DİL / LANGUAGE', switchTr: 'Türkçe', switchEn: 'İngilizceye geç', empty: 'Prometheus Core bağlantısı DESKTOP-002 içinde henüz yapılandırılmadı.', projectsEmpty: 'Güvenli çekirdek bağlantısı kurulduğunda projeler burada görünecek.', desktopLabel: 'Prometheus Masaüstü', ready: 'Hazır', offline: 'Çevrimdışı', authRequired: 'Kimlik doğrulama gerekli', protocolError: 'Protokol hatası', coreError: 'Core hatası', commandAccepted: 'Komut kabul edildi.', commandSubmitting: 'Gönderiliyor...', commandUnavailable: 'Core hazır değil.', commandUncertain: 'Çekirdek bağlantısı kesildi. Komut otomatik olarak yeniden gönderilmedi. Tekrar göndermeden önce görev etkinliğini kontrol edin.', commandFailed: 'Core komutu kabul edemedi.', requiresApproval: 'Onay gerekiyor', status: 'Durum', transport: 'Taşıma', loopbackOnly: 'Yalnızca loopback', localNativeBridge: 'Yerel native köprü', latestResult: 'Son komut', composerLabel: "Prometheus'a komut ver", composerHint: 'Ne yapmamı istediğinizi yazın.', composerPlaceholder: 'Örn. Bu projedeki son görev durumunu kontrol et ve bana özetle...', send: 'Gönder', sending: 'Gönderiliyor…', offlineHint: 'Komut göndermek için Prometheus Core bağlantısı gerekli.', authHint: 'Komutunuzu yazabilirsiniz. Çekirdek kimlik doğrulaması gerekli.', keyboardHint: 'Enter gönderir · Shift+Enter yeni satır', coreReady: 'Çekirdek hazır — komut gönderebilirsiniz.', coreOffline: 'Komutunuzu yazabilirsiniz. Göndermek için Prometheus Core bağlantısı bekleniyor.', coreAuthRequired: 'Komutunuzu yazabilirsiniz. Çekirdek kimlik doğrulaması gerekli.',
} as const;

const missionTranslations = {
  en: { missionControl: 'MISSION CONTROL', taskProgress: 'Task progression', pendingApproval: 'Pending approval', approvalNeedsReview: 'This action requires your review.', approve: 'Approve', reject: 'Reject', decisionSending: 'Updating…', missionLoadFailed: 'Mission could not be loaded.', decisionAccepted: 'Decision accepted by Core.', decisionUncertain: 'Decision delivery is uncertain. No automatic retry was made.' },
  tr: { missionControl: 'GÖREV KONTROLÜ', taskProgress: 'Görev ilerlemesi', pendingApproval: 'Bekleyen onay', approvalNeedsReview: 'Bu işlem için incelemeniz gerekiyor.', approve: 'Onayla', reject: 'Reddet', decisionSending: 'Güncelleniyor…', missionLoadFailed: 'Görev yüklenemedi.', decisionAccepted: 'Karar Core tarafından kabul edildi.', decisionUncertain: 'Kararın iletimi belirsiz. Otomatik tekrar yapılmadı.' },
} as const;
const reviewTranslations = { en: { changeReview: 'Change review', affectedFiles: 'Affected files', operations: 'Operations', preview: 'Preview', evidence: 'Evidence', refreshReview: 'Refresh review', reviewLoading: 'Loading review…', reviewUnavailable: 'Review evidence unavailable.', reviewTruncated: 'Review truncated.', reviewStale: 'Approval review is stale.' }, tr: { changeReview: 'Değişiklik incelemesi', affectedFiles: 'Etkilenen dosyalar', operations: 'İşlemler', preview: 'Önizleme', evidence: 'Kanıt', refreshReview: 'İncelemeyi yenile', reviewLoading: 'İnceleme yükleniyor…', reviewUnavailable: 'İnceleme kanıtı kullanılamıyor.', reviewTruncated: 'İnceleme kısaltıldı.', reviewStale: 'Onay incelemesi güncel değil.' } } as const;
type Widen<T> = { [K in keyof T]: T[K] extends string ? string : T[K] extends object ? Widen<T[K]> : T[K] };
export type TranslationDictionary = Widen<typeof englishTranslations> & Widen<typeof missionTranslations.en> & Widen<typeof reviewTranslations.en>;
export const translations: Record<Locale, TranslationDictionary> = { en: { ...englishTranslations, ...missionTranslations.en, ...reviewTranslations.en }, tr: { ...turkishTranslations, ...missionTranslations.tr, ...reviewTranslations.tr } };
